# Generated by Django 2.2.5 on 2020-10-23 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationmodel',
            name='annotator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annotationmodel',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mytoolapp.ProjectModel', verbose_name='プロジェクト'),
        ),
    ]
